[package]
name = "lune"
version = "0.1.0"
edition = "2024"
description = "A small offline crate to compute Moon Phases"


[dependencies]
chrono = "0.4.43"
clap = { version = "4.5.58", features = ["derive"] }
